import type { Metadata, Viewport } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import Script from 'next/script';
import './globals.css';
import { siteConfig } from '@/data/config';

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: 'Контент-фабрика — 50–150 вертикальных роликов в месяц',
  description: siteConfig.description,
  openGraph: {
    title: 'Контент-фабрика — 50–150 вертикальных роликов в месяц',
    description: siteConfig.description,
    type: 'website',
    locale: 'ru_RU',
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Контент-фабрика — 50–150 вертикальных роликов в месяц',
    description: siteConfig.description,
  },
  robots: { index: true, follow: true },
};

export const viewport: Viewport = {
  themeColor: '#0A0A0A',
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const ymId = process.env.NEXT_PUBLIC_YM_ID;

  return (
    <html
      lang="ru"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      style={
        {
          ['--font-sans' as string]: GeistSans.style.fontFamily,
          ['--font-mono' as string]: GeistMono.style.fontFamily,
        } as React.CSSProperties
      }
    >
      <body>
        {children}

        {ymId && (
          <Script id="yandex-metrika" strategy="afterInteractive">
            {`
              (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
              m[i].l=1*new Date();
              for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
              k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
              (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
              ym(${ymId}, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true });
            `}
          </Script>
        )}
      </body>
    </html>
  );
}
